#!/usr/bin/env python3
import json,subprocess,sys,tempfile
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT));from ailab.embeddings import HashingEmbedder;from ailab.rag_advanced import *;from ailab.store import SQLiteHybridStore;from ailab.text import chunk_document,load_documents
def main():
 with tempfile.TemporaryDirectory() as d:
  store=SQLiteHybridStore(Path(d)/"i.db",HashingEmbedder());docs=load_documents(ROOT/"examples/knowledge");store.upsert([c for doc in docs for c in chunk_document(doc,90,18)]);retriever=AdvancedRetriever(store);data=json.loads((ROOT/"examples/evaluation/rag-v1.json").read_text());cases=[RAGEvalCase(x["id"],x["query"],x["expected_source"]) for x in data["cases"]];evaluation=run_retrieval_eval(retriever,cases);cache=SemanticCache(Path(d)/"c.db",HashingEmbedder(),.8);cache.put("checkpoint replay","cached");hit=cache.get("checkpoint replay");sc=[{"name":"versioned_retrieval_eval","status":"passed" if evaluation["passed"] else "failed","evidence":evaluation},{"name":"semantic_cache","status":"passed" if hit else "failed","evidence":hit},{"name":"tenant_filter","status":"passed" if retriever.search("replay",filters={"tenant":"missing"})==[] else "failed"}]
 tests=subprocess.run([sys.executable,"-m","pytest","-q","tests/test_lab.py","tests/test_rag_advanced.py"],cwd=ROOT,text=True,capture_output=True);sc.append({"name":"project_1_tests","status":"passed" if tests.returncode==0 else "failed","stdout":tests.stdout.strip(),"stderr":tests.stderr.strip()});passed=sum(x["status"]=="passed" for x in sc);dest=ROOT/"artifacts/project-1-rag";dest.mkdir(parents=True,exist_ok=True);(dest/"latest.json").write_text(json.dumps({"summary":{"total":len(sc),"passed":passed,"failed":len(sc)-passed},"scenarios":sc},indent=2)+"\n");(dest/"latest.txt").write_text(f"Project 1 verification: {passed}/{len(sc)} passed\n");print(f"Project 1 verification: {passed}/{len(sc)} passed");return 0 if passed==len(sc) else 1
if __name__=="__main__":raise SystemExit(main())
